### ISSUE TITLE
can send, but not receive, messages

### ISSUE THREAD

**Issue by ebukh** [EionRobb/funyahoo-plusplus#18]
I downloaded the latest dll's as instructed in the readme for windows users. I can send messages to any user in my buddy list, and they are received by the recipient. They also show up in the web-based client. When the recipient responds, the response shows up in the web client, but not in pidgin. I'm using pidgin v.2.10.11

**Comment by dequis** [comment]
Go to the buddy list -> help menu -> select "debug window", copy and paste here the messages that appear in that window when you're supposed to receive a message.

**Comment by ebukh** [comment]
This is the entire exchange consisting of one message sent by me, and a response by the recipient (scroll down to 12:48:04)

[http://pastebin.com/ehi8gwTi](http://pastebin.com/ehi8gwTi)

**Comment by EionRobb** [comment]
That is worrisome that there is thousands of BatchSync/BatchAck calls being requested by the server! 

So the message from the recipient was" I'm receiving messages faster"? And this was messages to/from a group chat that were having problems? 
Do you happen to have that group chat in the buddy list with id RMK5IJG4ORHUPCFROIC7GNWBRI or were you trying to chat as a one-to-one conversation ? 

I'm just going to post the relevant section of the pastebin here
```
{"msg":"NewEntity","key":["Group","RMK5IJG4ORHUPCFROIC7GNWBRI","items","55B9B756C1C0008C"],"cn":1,"createdTime":1472752081671,"itemId":"55b9b756c1c0008c","message":"I'm receiving messages faster","type":"post","group":["Group","RMK5IJG4ORHUPCFROIC7GNWBRI"],"user":["User","KPOGP7NURCBZBIIDAPXN55MUOQ"],"likeCount":0}
```

**Comment by ebukh** [comment]
Yes, that was the response content. This was an individual message. I doubleclicked on the recipient's name in my buddy list, sent my message, and received one reply. the id of the recipient is "KPOGP7NURCBZBIIDAPXN55MUOQ".

**Comment by dequis** [comment]
>That is worrisome that there is thousands of BatchSync/BatchAck calls being requested by the server!

I get that behavior too, with normal conversations that work fine. 10 or so pairs of BatchSync/BatchAck after each sent message. I suspect it has something to do with the offset between seq and ack but not sure.

Stupid deceptively simple protocol.

**Comment by EionRobb** [comment]
> This was an individual message
Does it show that way in the web browser? Cos the message is saying it was intended for a group chat. Either that or type:group is the same as type:post and we need to handle the messages as such. 

We might need to get a pastebin of the very first (long) frame of data from the server when you first connect to the account,, which should have a list of all the group ids and what users they correspond with

> I get that behavior too
I'm wondering if this happens if there's more than one client connected to the server at the time (or if it thinks there's more than one). Just speculation though

**Comment by HankTheDrunk** [comment]
@EionRobb If you need a debug log I can email you mine.
Every time I send a message my debug window spams

I 've attached a slightly modified section of the debug text showing what happens when I send a message.
[yahoo-debug.txt](https://github.com/EionRobb/funyahoo-plusplus/files/450932/yahoo-debug.txt)

Thank you you and everyone who has contributed for the hard work on this plugin!

**Comment by dequis** [comment]
Yeah, you censored way too much, nothing useful in that log. Those identifiers you removed and the parts you cropped out are exactly the kind of thing we need to understand the issue:

>We might need to get a pastebin of the very first (long) frame of data from the server when you first connect to the account,, which should have a list of all the group ids and what users they correspond with

**Comment by ebukh** [comment]
> Does it show that way in the web browser

Yes, it does.

> pastebin of the very first (long) frame of data from the server when you first connect to the account

[http://pastebin.com/V6kwveMA](http://pastebin.com/V6kwveMA)

**Comment by EionRobb** [comment]
There's been a bunch of work recently to fix this.  Can you try again with a new libyahoo-plusplus.dll download from http://eion.robbmob.com/libyahoo-plusplus.dll

**Comment by Shdwdrgn** [comment]
Just wanted to comment that I've been watching this bug overnight as I was having the same issue (could send but not receive).  I pulled and compiled the new version this morning, and I am able to receive messages again on debian wheezy.  Thanks for all your work!

**Comment by ebukh** [comment]
can confirm this works now.

**Comment by dequis** [comment]
\o/
