### ISSUE TITLE
Are there any survivors out there?

### ISSUE THREAD

**Issue by Zombie-Ryushu** [EionRobb/funyahoo-plusplus#59]
Are there any survivors out there? Does anyone still use Yahoo Messenger in any capacity to make this protocol worth maintaining. If even one person comes forward and says this is needed still, Please let me know.

As for Classic AIM and Classic YIM, I think someone is making a server that backends to XMPP Out there for Classic AIM and Classic YIM Clients.

**Comment by wolfy67** [comment]
Me and all the partners I had ( which means around 250+ people ) have quit using YM 14 months ago. I tried for a couple of weeks to keep using YM as it was the de facto tool agreed upon by upper management but it was too flaky, lacked android support and soonish there was no one to talk to.

Absolutely everybody I know jumped ship and switched to other messengers ( FB / Whatsapp / Telegram / Viber ). I for one have not logged in YM since Feb 2017. I glimpsed over it via the web interface once or twice meanwhile but I quit doing even that.

**Comment by Zombie-Ryushu** [comment]
Was it Yahoo's plan to just kill the platform?

**Comment by FourthDr** [comment]
Yahoo messenger was a great app. I used it with Pidgin or with the official client which supported voice and video. Now it is a total POS! Totally devoid of any features at all and unusable. I blame Marissa Mayer for this situation. The moment she became CEO everything went to hell. She immediately started destroying Yahoo services, first groups, then email and finally messenger which was completely nuked. And for all this devastation she was rewarded with 1/4 of a billion dollars? How does someone get a job deal like that???! I hope she chokes on her reward!

Moving forward, if Verizon fixes or restores Yahoo messenger that would be great. But that remains to be seen. What other similar messaging services are there that work on a desktop as well as smart phones. Most seem to be for smart phones only. In the mean time I can't really use the replacement plugin because it keeps disconnecting and or crashing my pidgin client.

Zombie-Ryushu: tell me more about that XMPP backend. I haven't heard anything about that online anywhere. Wonder if it would be possible to restore contact lists? Probably not possible ha? But any restoration to a usable network with similar features would be welcomed. Seems like more and more of the internet is dying these days. Will there be anything left 20 years from now???

Just my two cents. Sorry if I want ranting. Just had to vent. I'm watching YOU Marissa Mayer! What a B**** >:-<

**Comment by Zombie-Ryushu** [comment]
Yahoo Instant Messenger is not coming back. Pidgin users are likely a large part of the reason. Pidgin users are seen as Parasites by the companies that run these services. When your service is totally cannibalized by Pidgin users, your service will get shut down because its now a cost center. 

I suspect the point of what Marissa Mayer has done is, is shut down YIM to make it so Pidgin users can't freeload. YM Plus Plus did work with for about 6 months, then they started fighting to knock the Pidgin users out. Every time EionRobb would fix it, two weeks later Yahoo would do something to make the Yahoo PlusPlus application stop working. Eventually EionRobb just quit trying.

So there will have to be someone that forks the Yahoo PlusPlus plugin and resumes getting it working again. Then Yahoo will start battling Pidgin again.

**Comment by FourthDr** [comment]
What was done to YM is more that just blocking Pidgin users. It destroyed the service completely for everyone. Ad blocking is not the reason I use Pidgin, I use it because I would rather have a single client that is open than dozens of over bloated clients that can only log on to one account at a time.

These companies should not complain about people blocking ads. They brought it upon themselves by going way overboard with ads to the point of using almost every piece of visual real-estate to serve active scripted ad content riddled with viruses/malware/0-day attack code to where people have no choice but to block everything. I don't mind ads as long as they're unobtrusive. I DO MIND being attacked with ads full a malicious code. A perfect example is Yahoo search, which recently was called "unusable" in a recent news story (https://www.ghacks.net/2018/01/02/yahoo-search-becomes-unusable-because-of-ads/).

And it's not just messenger that was messed up, every single service on Yahoo was wrecked in one way or another which has nothing to do with Pidgin or ad blocking. I would say it's the total incompetence of Yahoo management that is a the cause of their problems. They don't have a clue. Paying Marissa Mayer 1/4 of a billion is proof of that. 

Ranting again. But I'm just totally incensed about it. Seems it all could have totally been avoided in the first place with the right people running things.

**Comment by Zombie-Ryushu** [comment]
As for the XMPP thing...

There is a user on IRC that wrote an OSCAR server for Windows that works with YIM and AIM. It works better for AIM than for YIM. Currently its "local only" as in only clients connected to this server can talk. It doesn't bridge to anything else. There are plans this person had to allow it to uplink to an XMPP server and enumerate XMPP users as Buddies. But this is only speculation at that point. 

If he succeeded, it would mean that anything XMPP would be enumerated in YIM and AIM's last official Clients. Given that Spectrum 2 exists, this means that you could use AIM or YIM to chat with anyone on Skype, Discord, Hangouts, FaceBook, or any other service in which a libpurple module exists Spectrum 2 can communicate with.

This already works with Conversations on Android as a means to block ads, and stop their apps from extracting location info from Android Devices. Conversations is just an XMPP service.

But there is a kiss of death with this Project: The Programmer is a Windows Programmer. Thats fatal. Considering the XMPP servers, and Spectrum2 are Linux Applications.

If you use Pidgin, this program is equally pointless. Why connect to the OSCAR Server when you can just connect to the XMPP service behind it?

**Comment by FourthDr** [comment]
What was done to YM is more that just blocking Pidgin users. It destroyed the service completely for everyone. Ad blocking is not the reason I use Pidgin, I use it because I would rather have a single client that is open than dozens of over bloated clients that can only log on to one account at a time.

These companies should not complain about people blocking ads. They brought it upon themselves by going way overboard with ads to the point of using almost every piece of visual real-estate to serve active scripted ad content riddled with viruses/malware/0-day attack code to where people have no choice but to block everything. I don't mind ads as long as they're unobtrusive. I DO MIND being attacked with ads full a malicious code. A perfect example is Yahoo search, which was recently call "unusable" in a recent news story (https://www.ghacks.net/2018/01/02/yahoo-search-becomes-unusable-because-of-ads/).

And it's not just messenger that was messed up, every single service on Yahoo was wrecked in one way or another which has nothing to do with Pidgin. I would say it's the total incompetence of Yahoo management that is a the cause of their problems. They don't have a clue. Paying Marissa Mayer 1/4 of a billion is proof of that.

**Comment by FourthDr** [comment]
Well, hopefully something will be figured out in the new year. Maybe a decentralized bittorrent/blockchain universal messaging client/server system of some sort. Privacy + Security + Decentralized + permanent. No more network shutdowns. One can only hope.

**Comment by Zombie-Ryushu** [comment]
You just described XMPP as it was intended to be. A loose Federation of multiple Nets, encrypted with SSL, supporting voice and Video, only Pidgin on Linux and Ekiga are known to support Voice and Video. 

FaceBook supported XMPP for a while. It cut into their Revenue, so they discontinued it. Google Talk was entirely based on XMPP. 

XMPP works, but XMPP represents a threat to the revenue stream of advertising platforms like FaceBook, Google and Yahoo.

**Comment by FourthDr** [comment]
Why is voice and video only supported on Linux? I knew Google supported XMPP. I'm waiting for jabber.org to enable automatic account creation. That's supposed to happen some time in early 2018. As for FaceSPOOK AKA F***upbook that's nothing but spyware, I will NEVER use that EVER!

**Comment by Shdwdrgn** [comment]
My last contact from Yahoo finally agreed that the service was no longer reliable and switched over to pidgin/google so we could chat again.  I still check in here every now and then, but the comments above pretty well convey that any possible connection to YIM is pointless and not worth pursuing.  I'll still keep checking in just to see if anything has changed, but I won't hold my breath.

@FourthDr -- keep in mind that these changes were not made by the Yahoo team (who reliably ran YIM and other services for decades), but rather the fault of their new Verizon overlords.  While I was never a big fan of Yahoo in general, I do believe in placing the blame where it is due.

**Comment by Zombie-Ryushu** [comment]
@FourthDr: On Linux, Pidgin is linked into some specific Libraries from Ekiga called the FarStream Libraries. This allows Pidgin to use Ekiga's Protocols over XMPP with the assistance of a SPIN/TURN Server to get around NAT related issues. 

On Windows the FarStream Libraries aren't present. 

As for Yahoo, I didn't get a chance to get Contact info for everyone I lost when Yahoo went dark. Thats the only reason I am still interested.

**Comment by sam404** [comment]
Me I guess because I only joined Yahoo Messenger after this big update. However I'm looking for something not Google or Yahoo that I can use instead and I can use with Pidgin.

**Comment by macexpertsusa** [comment]
Are there any survivors out there?         YES

**Comment by Zombie-Ryushu** [comment]
Going to need more help/commits/patches/forks.

**Comment by Zombie-Ryushu** [comment]
It works again. Hooray!
