### ISSUE TITLE
Messages not shown

### ISSUE THREAD

**Issue by alexolog** [EionRobb/funyahoo-plusplus#6]
Steps to reproduce:
1. Create an "old" yahoo account A
2. Create a "Yahoo 2016" account B
3. Login to account B
4. Message account A from account B
5. Login to account A
6. Message account A from account B again

Expected result:
Another tab opens, user can message one account from the other

Observed result:
Debug window shows activity but no tab opens

**Comment by dequis** [comment]
I'm pretty sure this is in the "blame yahoo" territory. Think of this as a completely different IM network that happens to share usernames.

**Comment by alexolog** [comment]
When I login to Account A on Yahoo email web site, I am able to message Account B on Pidgin.  Similarly, logging in to Account B on Yahoo email web site and messaging Account A on Pidgin.

So there must be a bridge between the separate networks.

**Comment by EionRobb** [comment]
Unless you added the yahoo user to your buddy list using their long and random-looking id number (26 characters of upper case alphanumeric characters) you're not going to be able to send them a message, as I haven't added any way of converting between the 'messenger id' (like 'eionrobb') and the 'user id' (like '36HY3HZBURIUMO4Y4LST6HRVOI')


Actually, even if you do add their user id I don't think it'll work, because I haven't added any way of creating a new chat room if one doesn't exist already.

The workaround at the moment is to send a message on messenger.yahoo.com, or get them to message you first, and then continue the conversation with Pidgin.

**Comment by EionRobb** [comment]
https://github.com/EionRobb/funyahoo-plusplus/commit/3a524055f7d17c2a367657097b777fb14e006c7f has fixes so that you can add a user to your buddy list with their yahoo id and it should convert it into the user id

**Comment by alexolog** [comment]
Great!  Thank you!
By Yahoo ID I assume you mean the email address.
Also, please provide a DLL.

**Comment by EionRobb** [comment]
> By Yahoo ID I assume you mean the email address.

No, I mean the yahoo id like "eionrobb" but I've just added support for adding people by their email address

> Also, please provide a DLL.

I've updated the front page readme with instructions about that

**Comment by dequis** [comment]
If i'm reading this right, this is solved already. If that is not correct, comment and we'll reopen. Also remember to test with the latest revision.
